[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psp-auth"
version = "0.1.0"
dependencies = [
    "joserfc>=1.3.4,<2.0",
    "fastapi[standard]>=0.117.1,<0.118",
    "starlette>=0.48.0,<0.49.0",
    "httpx>=0.28.1,<0.29.0",
    "itsdangerous>=2.2.0,<3.0",
]
requires-python = ">=3.12"

description = "A Python library for authentication and authorisation in the PSP platform"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["psp", "auth", "authentication", "authorisation", "authorization"]

[project.urls]
Homepage = "https://github.com/Portfolio-Solver-Platform/python-auth-lib"

[tool.setuptools.packages.find]
where = ["src"]
include = ["psp_auth*"]
exclude = ["tests*"]

[project.optional-dependencies]
dev = [
    "pytest>=8,<9",
    "pytest-cov>=7,<8",
    "ruff>=0.13.2,<0.14.0",
    "bandit>=1.7,<2.0",
    "pip-audit>=2.7,<3.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
