name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Lint
      run: ruff check . --no-cache

    - name: Run tests
      run: pytest

    - name: Audit code
      run: bandit . -qrx ./tests

    - name: Dependency audit
      run: pip-audit --ignore-vuln GHSA-4xh5-x5gv-qwph
